# Generated by Django 5.0.1 on 2024-03-09 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_payment_options_payment_stripe_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='stripe_id',
        ),
    ]
