# Generated by Django 5.0.1 on 2024-03-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_course_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(null=True, verbose_name='Цена'),
        ),
    ]
