# Generated by Django 5.0.1 on 2024-03-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_course_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название продукта')),
                ('price_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена платежа')),
                ('payment_link', models.URLField(blank=True, max_length=400, null=True, verbose_name='Ссылка на оплату')),
                ('payment_id', models.CharField(max_length=255, unique=True, verbose_name='Идентификатор платежа')),
            ],
            options={
                'verbose_name': 'Оплата курса',
                'verbose_name_plural': 'Оплата курсов',
            },
        ),
    ]
