# Generated by Django 5.0.1 on 2024-03-13 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_coursepayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoursePayment',
        ),
    ]
